config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "peeps#index"
  resources :peeps do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :peep
end

app/models/peep.rb
class Peep < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :body, presence: true, length: { minimum: 1 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @peep = Peep.find(params[:peep_id])
    @comment = @peep.comments.create(comment_params)
    redirect_to peep_path(@peep)
  end

  def destroy 
    @peep = Peep.find(params[:peep_id])
    @comment = @peep.comments.find(params[:id])
    @comment.destroy
    redirect_to peep_path(@peep)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/peeps_controller.rb
class PeepsController < ApplicationController
  def index
    @peeps = Peep.all
  end

  def show
    @peep = Peep.find(params[:id])
  end

  def new 
    @peep = Peep.new
  end

  def create
    @peep = Peep.new(peep_params)

    if @peep.save
      redirect_to @peep
    else
      render :new
    end
  end

  def edit
    @peep = Peep.find(params[:id])
  end

  def update
    @peep = Peep.find(params[:id])

    if @peep.update(peep_params)
      redirect_to @peep
    else
      render :edit
    end
  end

  def destroy
    @peep = Peep.find(params[:id])
    @peep.destroy

    redirect_to root_path
  end

  private 

   def peep_params
      params.require(:peep).permit(:body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/peeps_helper.rb
module PeepsHelper
end

app/views/comments/_comment.html.erb
<p> 
<strong>by</strong>
<%= comment.commenter%>
<strong>:</strong>
<%=comment.body%>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.peep, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @peep, @peep.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/peeps/_form.html.erb
<%= form_with model: peep do |form| %>
  <div>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
    <% peep.errors.full_messages_for(:body).each do |message| %>
    <div><%= message %></div>
    <%end%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/peeps/edit.html.erb
<h1>Edit Peep</h1>

<%= render "form", peep: @peep %>

app/views/peeps/index.html.erb
<ul>
<% @peeps.each do |peep| %>
<li> <%=link_to peep.body, peep%> </li>
<%end%>
</ul>

<%= link_to "New Peep", new_peep_path %>

app/views/peeps/new.html.erb
<h1>New Peep</h1>

<%= form_with model: @peep do |form| %>
  <div>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
    <% @peep.errors.full_messages_for(:body).each do |message| %>
    <div><%= message %></div>
    <%end%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/peeps/show.html.erb
<p> <%= @peep.body %> </p>

<ul>
  <li><%= link_to "Edit", edit_peep_path(@peep) %></li>
  <li><%= link_to "Delete", peep_path(@peep), method: :delete, data: { confirm: "Are you sure?" }%></li>
</ul>

<%# <h2>Comments</h2> %>
<%= render @peep.comments %>

<h3>respond</h3>
<%= render 'comments/form' %>